### ISSUE TITLE
Gradio Application isn't working properly. Throws error on uploading and running any audio file.

### ISSUE THREAD

**Issue by Siddharth1698** [jaeyeonkim99/EnCLAP#1]
<img width="797" alt="image" src="https://github.com/jaeyeonkim99/EnCLAP/assets/31384057/7a6b187c-3b05-46f5-9077-524d291dc2ba">

**Comment by jaeyeonkim99** [comment]
Hello! 
I've just checked the logs for the demo and found out the error occurred during the audio processing, maybe due to a different audio format from what we expected. I've also checked that the demo worked properly with the audio files I have.

Can you provide details(file format, channels, encoding, ...) of the audio files you tried? Or can you give us the audio files you tried?

**Comment by Siddharth1698** [comment]
Thank you. I could get it running by converting my audio to 16khz, mono, wav format. 
I think it would be nice if you could add this pre-processing step before, since many people might end up just using the audio they have instead of converting it to this particular format.

**Comment by jaeyeonkim99** [comment]
Thank you for your suggestion!
Now we support mono and stereo .wav files with various sample rates. We will add more support for various audio file formats.
The model we used for the demo is the EnCLAP-base model trained on both AudioCaps and Clotho.
